version: '3'

dotenv:
  - .env

tasks:
  # prepare:
  #   cmd: go mod tidy

  # lint:
  #   cmds:
  #     - golangci-lint run ./cmd

  # test:
  #   cmds:
  #     - go test -cover ./cmd

  # compile:
  #   cmd: GOOS=linux go build -o ./bin/goapp ./goapp

  build:
    cmds: 
      - docker build --pull --rm -f ./bookworm.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest .
      - docker build --pull --rm -f ./golang.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}-bookworm .

  push:
    cmds:
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}-bookworm
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest
      

  deploy:
    cmds: 
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

  release:
    cmds:
      #- task: prepare
      #- task: lint
      #- task: test
      #- task: compile
      - task: build
      - task: push
      - task: deploy